name: Git-Assembler

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - 'v*-boto3'

jobs:
  assembler:
    name: Generate master using Git-Assembler
    runs-on: ubuntu-latest
    steps:
      - name: Install System Deps
        run: 'sudo apt-get update && sudo apt-get install -y git'

      - name: Install Git-Assembler
        run: |
          git clone https://gitlab.com/wavexx/git-assembler git-assembler
          sudo install -m 0755 git-assembler/git-assembler /usr/local/bin/
          rm -rf git-assembler

      - uses: actions/checkout@v2
        with:
          ref: wip/boto3_master

      - name: Assemble master
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote add upstream "https://github.com/saltstack/salt.git"
          git fetch --all
          git assembler --config .git-assembly --assemble --verbose --create
          git checkout master
          git push --verbose --force origin master

      - name: Update Releases
        run: |
          git fetch --all
          TAGS="$(git tag -l | grep -P '^v3\d\d\d\d*' | grep -Pv '\drc\d+' | grep -v '_docs$')"
          for tag in ${TAGS}; do
            git checkout master
            echo "Tagging ${tag}-boto3"
            git branch --force wip/boto3-tmp-tagging "${tag}"
            git checkout wip/boto3-tmp-tagging
            git rev-list --reverse upstream/master...master | git cherry-pick --stdin
            git tag --force "${tag}-boto3"
          done
          git checkout master
          git branch -D wip/boto3-tmp-tagging
          git push -f --tags
